### PR TITLE
Expose more properties and generic send_command function

### PR DESCRIPTION
**Pull request by jnxxx**
Changes are:

1. A preparation for at least a partly fix for danfoss_ally issue #44.

2. Aditionally, it exposes some additional properties and a new generic send_command function to support new functionality.

### CODE REVIEW

**Comment by jnxxx** [comment]
@MTrab , will this version automatically appear on [pypi.org](https://pypi.org/project/pydanfossally/)?

**Comment by MTrab** [comment]
Should already be there

**Comment by jnxxx** [comment]
I see v0.0.27 as the latest one, updated in July.

**Comment by MTrab** [comment]
That's strange. Will take a look when back from vacation

**Comment by MTrab** [comment]
Should be fixed now - or at least the version should be uploading to PyPI

**Pull request merged**
